name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "run the code"

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build using docker
        run: echo "Docker running"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running the test
        run: echo "test occur"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploying the code
        run: echo "code Deploying"






        
