name: Auto Linter

on:
  push:
    paths:
      - "**.py"

jobs:
  code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Install linter
        run: pip install ruff

      - name: Check the files for linting
        run: ruff check . --fix
